language: go
go:
  - tip

before_install: 
  - echo "before install"

script:
  - mkdir releases
  - echo `date -u` > releases/file.txt
  - "cat <<EOT >> releases/file.txt
    ## releases
    `date -u`
    EOT"
    

before_deploy:
  

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: releases.fader.inpime.com
    endpoint: releases.fader.inpime.com.s3-website.eu-central-1.amazonaws.com
    region: eu-central-1
    skip_cleanup: true
    upload-dir: travis-builds
    local-dir: releases
    acl: public_read
    detect_encoding: true
    cache_control: max-age=0
    on:
      tags: false
      branch: release
  - provider: releases
    api_key: $GITHUB_TOKEN_KEY
    skip_cleanup: true
    provider: releases
    file:
      - "releases/README.md"
      - "releases/file.txt"
    on:
      tags: false
      branch: master
